apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: news_request_queue  # This name is referenced in application code
  namespace: default
spec:
  type: bindings.rabbitmq
  version: v1
  metadata:
  - name: host
    value: "amqp://rabbitmq:5672"  # Адрес RabbitMQ сервера
  - name: queueName
    value: "news_request_queue"  # Имя очереди
  - name: durable
    value: "true"  # Очередь сохраняется после перезапуска
  - name: autoAck
    value: "false"  # Ручное подтверждение обработки сообщений
  - name: prefetchCount
    value: "10"  # Количество сообщений, обрабатываемых одновременно

