apiVersion: dapr.io/v1alpha1
kind: Resiliency
metadata:
  name: rabbitmq-binding-retry
  namespace: default
spec:
  policies:
    retries:
      no-retry:
        policy: constant
        backoffDuration: "0s"
        maxRetries: 0
      limited-retry:
        policy: exponential
        backoffDuration: "200ms"
        maxRetries: 3
      aggressive-retry:
        policy: constant
        backoffDuration: "100ms"
        maxRetries: 5
  targets:
    components:
      rabbitmq-binding:
        retries: limited-retry
    apps:
      user-manager:
        retries: aggressive-retry
      news-manager:
        retries: limited-retry
      message_handler:
        retries: no-retry
      ai_summarizer:
        retries: no-retry
      collector:
        retries: aggressive-retry
      users_db:
        retries: limited-retry


