services:
  user-service:
    build:
      context: ./user-service
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/user_service
    depends_on:
      - mongodb
    networks:
      - backend
    command: ["dapr", "run", "--app-id", "user-service", "--app-port", "5001", "--", "python", "app.py"]

  news-service:
    build:
      context: ./news-service
    ports:
      - "5002:5002"
    environment:
      - NEWS_API_KEY=your_news_api_key
    depends_on:
      - redis
    networks:
      - backend
    command: ["dapr", "run", "--app-id", "news-service", "--app-port", "5002", "--", "python", "app.py"]

  mongodb:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - backend

  component-manager:
    build:
      context: ./managers
    container_name: component-manager
    ports:
      - "5000:5000"
    depends_on:
      - user-service
      - news-service
    environment:
      - DAPR_HTTP_PORT=3500
    networks:
      - backend
    command: ["dapr", "run", "--app-id", "component-manager", "--app-port", "5000", "--", "python", "component_manager.py"]

volumes:
  mongodb-data:
    driver: local
  redis-data:
    driver: local

networks:
  backend:
    driver: bridge
